python_file = open("try_except.py","r")
# reading from the file
print(python_file.read())
python_file.close()